# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui

font = QtGui.QFont()
font.setFamily("Arial")
font.setPointSize(10)


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(400, 150)
        SettingsWindow.setMinimumSize(QtCore.QSize(400, 150))
        SettingsWindow.setMaximumSize(QtCore.QSize(400, 150))
        self.gridLayout_2 = QtWidgets.QGridLayout(SettingsWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(SettingsWindow)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.banner_settings = QtWidgets.QCheckBox(self.widget)
        self.banner_settings.setObjectName("banner_settings")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.banner_settings)
        self.terminal_output = QtWidgets.QCheckBox(self.widget)
        self.terminal_output.setObjectName("terminal_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.terminal_output)
        self.line = QtWidgets.QFrame(self.splitter)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelBitrate = QtWidgets.QLabel(self.widget1)
        self.labelBitrate.setObjectName("labelBitrate")
        self.gridLayout.addWidget(self.labelBitrate, 0, 0, 1, 1)
        self.bitrate_settings = QtWidgets.QSpinBox(self.widget1)
        self.bitrate_settings.setSpecialValueText("")
        self.bitrate_settings.setMinimum(1000)
        self.bitrate_settings.setMaximum(30000)
        self.bitrate_settings.setSingleStep(1000)
        self.bitrate_settings.setObjectName("bitrate_settings")
        self.gridLayout.addWidget(self.bitrate_settings, 0, 1, 1, 1)
        self.labelKey = QtWidgets.QLabel(self.widget1)
        self.labelKey.setObjectName("labelKey")
        self.gridLayout.addWidget(self.labelKey, 1, 0, 1, 1)
        self.KeyEdit = QtWidgets.QLineEdit(self.widget1)
        self.KeyEdit.setObjectName("KeyEdit")
        self.gridLayout.addWidget(self.KeyEdit, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 2)
        self.OkButton = QtWidgets.QPushButton(SettingsWindow)
        self.OkButton.setObjectName("OkButton")
        self.gridLayout_2.addWidget(self.OkButton, 1, 0, 1, 1)
        self.CancelButton = QtWidgets.QPushButton(SettingsWindow)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout_2.addWidget(self.CancelButton, 1, 1, 1, 1)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Параметры команд"))
        self.banner_settings.setText(_translate("SettingsWindow", "Показывать баннер FFmpeg"))
        self.terminal_output.setText(_translate("SettingsWindow", "Выводить строку с командой в терминал"))
        self.labelBitrate.setText(_translate("SettingsWindow", "Битрейт"))
        self.bitrate_settings.setSuffix(_translate("SettingsWindow", " КБит/с"))
        self.labelKey.setText(_translate("SettingsWindow", "Ключ M3U8"))
        self.OkButton.setText(_translate("SettingsWindow", "Ok"))
        self.CancelButton.setText(_translate("SettingsWindow", "Отмена"))
