# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ffmpegConverterMain(object):
    def setupUi(self, ffmpegConverterMain):
        ffmpegConverterMain.setObjectName("ffmpegConverterMain")
        ffmpegConverterMain.resize(556, 240)
        ffmpegConverterMain.setMinimumSize(QtCore.QSize(320, 240))
        self.centralwidget = QtWidgets.QWidget(ffmpegConverterMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.lineEditPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPath.setText("")
        self.lineEditPath.setObjectName("lineEditPath")
        self.pathLayout.addWidget(self.lineEditPath)
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAdd.setDefault(True)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pathLayout.addWidget(self.pushButtonAdd)
        self.verticalLayout.addLayout(self.pathLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.keyLayout = QtWidgets.QHBoxLayout()
        self.keyLayout.setObjectName("keyLayout")
        self.lineEditKey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditKey.setInputMask("")
        self.lineEditKey.setObjectName("lineEditKey")
        self.keyLayout.addWidget(self.lineEditKey)
        self.pushButtonConvert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConvert.setDefault(True)
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        self.keyLayout.addWidget(self.pushButtonConvert)
        self.verticalLayout.addLayout(self.keyLayout)
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)
        ffmpegConverterMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ffmpegConverterMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 24))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ffmpegConverterMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ffmpegConverterMain)
        self.statusbar.setObjectName("statusbar")
        ffmpegConverterMain.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(ffmpegConverterMain)
        self.actionInfo.setObjectName("actionInfo")
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ffmpegConverterMain)
        QtCore.QMetaObject.connectSlotsByName(ffmpegConverterMain)

    def retranslateUi(self, ffmpegConverterMain):
        _translate = QtCore.QCoreApplication.translate
        ffmpegConverterMain.setWindowTitle(_translate("ffmpegConverterMain", "FFmpeg Converter"))
        self.lineEditPath.setPlaceholderText(_translate("ffmpegConverterMain", "Select the movie..."))
        self.pushButtonAdd.setText(_translate("ffmpegConverterMain", "Add"))
        self.lineEditKey.setPlaceholderText(_translate("ffmpegConverterMain", "Enter your key here..."))
        self.pushButtonConvert.setText(_translate("ffmpegConverterMain", "Convert"))
        self.labelStatus.setText(_translate("ffmpegConverterMain", "<html><head/><body><p><span style=\" font-size:14pt;\">Status</span></p></body></html>"))
        self.menuHelp.setTitle(_translate("ffmpegConverterMain", "Help"))
        self.actionInfo.setText(_translate("ffmpegConverterMain", "Instruction"))
